<a href="https://colab.research.google.com/github/AvnishR4j/AvnishRaj_1024170125_UCS420/blob/main/Assignment_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

## Q.1: 1D-array with 5 elements and basic operations

In [2]:
# Create a NumPy 1D-array with 5 elements
array_1d = np.array([10, 20, 30, 40, 50])
print(f"Original array: {array_1d}")

# a) Addition of 2 in all the elements
added_array = array_1d + 2
print(f"Array after adding 2: {added_array}")

# b) Multiply 3 with all the elements
multiplied_array = array_1d * 3
print(f"Array after multiplying by 3: {multiplied_array}")

# c) Divide every element by 2
divided_array = array_1d / 2
print(f"Array after dividing by 2: {divided_array}")

Original array: [10 20 30 40 50]
Array after adding 2: [12 22 32 42 52]
Array after multiplying by 3: [ 30  60  90 120 150]
Array after dividing by 2: [ 5. 10. 15. 20. 25.]


## Q.2: Questions on Basic NumPy Array (Reverse, Most Frequent Value)

In [3]:
# a) Reverse the NumPy array
arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]
print(f"Original array: {arr}")
print(f"Reversed array: {reversed_arr}")

# b) Find the most frequent value and their indice(s)
# Helper function to find most frequent value and its indices
def find_most_frequent(arr):
    values, counts = np.unique(arr, return_counts=True)
    max_count_idx = np.argmax(counts)
    most_frequent_value = values[max_count_idx]
    indices = np.where(arr == most_frequent_value)[0]
    return most_frequent_value, indices

# i. x = np.array([1,2,3,4,5,1,2,1,1,1])
x = np.array([1,2,3,4,5,1,2,1,1,1])
most_freq_x_val, most_freq_x_indices = find_most_frequent(x)
print(f"\nArray x: {x}")
print(f"Most frequent value in x: {most_freq_x_val}")
print(f"Indices of most frequent value in x: {most_freq_x_indices}")

# ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
most_freq_y_val, most_freq_y_indices = find_most_frequent(y)
print(f"\nArray y: {y}")
print(f"Most frequent value in y: {most_freq_y_val}")
print(f"Indices of most frequent value in y: {most_freq_y_indices}")

Original array: [1 2 3 6 4 5]
Reversed array: [5 4 6 3 2 1]

Array x: [1 2 3 4 5 1 2 1 1 1]
Most frequent value in x: 1
Indices of most frequent value in x: [0 5 7 8 9]

Array y: [1 1 1 2 3 4 2 4 3 3]
Most frequent value in y: 1
Indices of most frequent value in y: [0 1 2]


## Q.3: Access elements of a 2-D array

In [4]:
# For the given 2-D array
arr_2d = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(f"Original 2-D array:\n{arr_2d}")

# a) Access 1st row, 2nd column (index 0, 1)
# NumPy uses 0-based indexing.
# So, 1st row is index 0, and 2nd column is index 1.
element_a = arr_2d[0, 1]
print(f"\nElement at 1st row, 2nd column: {element_a}")

# b) Access 3rd row, 1st column (index 2, 0)
# So, 3rd row is index 2, and 1st column is index 0.
element_b = arr_2d[2, 0]
print(f"Element at 3rd row, 1st column: {element_b}")

Original 2-D array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

Element at 1st row, 2nd column: 20
Element at 3rd row, 1st column: 70


## Q.4: 1-D NumPy array using `linspace()`, properties and transpose

In [5]:
# Write program to create an 1-D NumPy array named <<Your Name>> with evenly
# spaced 25 numbers from 10 to 100 using linspace().
# Let's use 'MyNameArray' as a placeholder for 'Your Name'
my_name_array = np.linspace(10, 100, 25)
print(f"1-D array: {my_name_array}")

# Print the dimensions of the array
print(f"\nDimensions (ndim): {my_name_array.ndim}")

# Print shape
print(f"Shape: {my_name_array.shape}")

# Print total elements
print(f"Total elements (size): {my_name_array.size}")

# Print the data type of each element
print(f"Data type of each element (dtype): {my_name_array.dtype}")

# Print total number of bytes consumed by the array
print(f"Total bytes consumed: {my_name_array.nbytes}")

# Find the transpose of this array using reshape() attribute.
# A 1D array has a shape of (n,). To get a transpose-like effect, we can reshape it to (1, n) and then transpose.
# Or, more directly, reshape to (n, 1).
reshaped_transpose = my_name_array.reshape(-1, 1) # Reshape to a column vector
print(f"\nTranspose using reshape(-1, 1):\n{reshaped_transpose}")
print(f"Shape of reshaped transpose: {reshaped_transpose.shape}")

# Can we do the same with T attribute?
# For a 1-D array, the .T attribute returns the array unchanged because its 'transpose' is itself.
# However, if we first make it a 2D array (e.g., a row vector or column vector), then .T will work as expected.

# Example 1: .T on a true 1D array
print(f"\nTranspose of 1D array using .T: {my_name_array.T}")
print(f"Shape of 1D array using .T: {my_name_array.T.shape}") # Still (25,)

# Example 2: .T on a 2D row vector (shape (1, n))
row_vector = my_name_array[np.newaxis, :]
print(f"\nOriginal row vector (shape {row_vector.shape}):\n{row_vector}")
print(f"Transpose of row vector using .T (shape {row_vector.T.shape}):\n{row_vector.T}")

# Conclusion for .T attribute on 1D arrays:
print("\nFor a strictly 1-D array, the `.T` attribute does not change its shape or content (it returns itself).\
It is primarily useful for 2-D and higher-dimensional arrays. To get a 'transposed' view of a 1-D array\
into a 2-D form (like a column vector), one must first reshape it to a 2-D array (e.g., `array.reshape(-1, 1)`)\
and then optionally apply `.T` if further transposition is needed (though not strictly necessary after `reshape(-1, 1)`)."
)

1-D array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]

Dimensions (ndim): 1
Shape: (25,)
Total elements (size): 25
Data type of each element (dtype): float64
Total bytes consumed: 200

Transpose using reshape(-1, 1):
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Shape of reshaped transpose: (25, 1)

Transpose of 1D array using .T: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Shape of 1D array using .T: (25,)

Original row vector (shape (1, 25)):
[[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
   

## Q.5: Create a 2-D Array, compute stats, reshape, and resize

In [6]:
# Create a 2-D Array of three rows and four columns, named ucs420_<your_name>>
# with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35.
# Let's use 'ucs420_MyName' as a placeholder.
values = [10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35]
ucs420_MyName = np.array(values).reshape(3, 4)
print(f"Original 2-D array (ucs420_MyName):\n{ucs420_MyName}")

# Compute the mean, median, max, min, unique elements.
print(f"\nMean of the array: {np.mean(ucs420_MyName)}")
print(f"Median of the array: {np.median(ucs420_MyName)}")
print(f"Maximum element: {np.max(ucs420_MyName)}")
print(f"Minimum element: {np.min(ucs420_MyName)}")
print(f"Unique elements: {np.unique(ucs420_MyName)}")

# Reshape the array to four rows and three columns
# and name it as reshaped_ucs420_<your_name>>.
reshaped_ucs420_MyName = ucs420_MyName.reshape(4, 3)
print(f"\nReshaped array (4x3):\n{reshaped_ucs420_MyName}")

# Resize the array to two rows and three columns
# and name it as resized_ucs420_<your_name>>.
# np.resize creates a new array with the specified shape.
# If the new array is larger, it's filled with copies of the original array.
# If smaller, the new array will contain only the first elements.
resized_ucs420_MyName = np.resize(ucs420_MyName, (2, 3))
print(f"\nResized array (2x3):\n{resized_ucs420_MyName}")

Original 2-D array (ucs420_MyName):
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]

Mean of the array: 43.333333333333336
Median of the array: 37.5
Maximum element: 90
Minimum element: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped array (4x3):
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized array (2x3):
[[10 20 30]
 [40 50 60]]
